### ISSUE TITLE
dest.on is not a function

### ISSUE THREAD

**Issue by silenceisgolden** [imagemin/imagemin-pngquant#10]
```
TypeError: dest.on is not a function
    at DestroyableTransform.Readable.pipe (/Users/AJ/dev/bz/lifesgreatestquestion.com/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:516:8)
    at Gulp.<anonymous> (/Users/AJ/dev/bz/lifesgreatestquestion.com/gulpfile.js:256:6)
    at module.exports (/Users/AJ/dev/bz/lifesgreatestquestion.com/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/AJ/dev/bz/lifesgreatestquestion.com/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/AJ/dev/bz/lifesgreatestquestion.com/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/AJ/dev/bz/lifesgreatestquestion.com/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/AJ/npm/lib/node_modules/gulp/bin/gulp.js:129:20
    at doNTCallback0 (node.js:415:9)
    at process._tickCallback (node.js:344:13)
    at Function.Module.runMain (module.js:474:11)
    at startup (node.js:124:18)
    at node.js:959:3
```

using io.js 2.0.1

**Comment by silenceisgolden** [comment]
just missed the second set of parentheses in the function call, closing
