### ISSUE TITLE
TypeError of steam in 5.0.0

### ISSUE THREAD

**Issue by Takafumi-Yamashita** [imagemin/imagemin-pngquant#25]
Hi, I faced the problem in this package through [gulp-imagemin](https://github.com/sindresorhus/gulp-imagemin).

```
gulp.task('imagemin', function() {
  return gulp.src('src/images/*.{png,jpeg,gif}')
    .pipe(imagemin({
      progressive: true,
      svgoPlugins: [
        { removeViewBox: false },
        { cleanupIDs: false }
      ],
      use: [pngquant()]
    }))
    .pipe(gulp.dest('public/images'));
});
```

I run `gulp imagemin`, and then console outputs were as follows;

```
/myproject/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/readable-stream/lib/_stream_readable.js:740
  stream.on('end', function () {
         ^

TypeError: stream.on is not a function
    at Readable.wrap (/myproject/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/readable-stream/lib/_stream_readable.js:740:10)
    at wrap (/myproject/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/index.js:67:29)
    at combine (/myproject/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/index.js:29:18)
    at Function.module.exports.obj (/myproject/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/index.js:22:10)
    at Imagemin.createStream (/myproject/node_modules/gulp-imagemin/node_modules/imagemin/index.js:103:24)
    at Imagemin.run (/myproject/node_modules/gulp-imagemin/node_modules/imagemin/index.js:77:20)
    at DestroyableTransform.through.obj.percent (/myproject/node_modules/gulp-imagemin/index.js:56:12)
    at DestroyableTransform._transform (/myproject/node_modules/gulp-imagemin/node_modules/through2-concurrent/through2-concurrent.js:29:15)
    at DestroyableTransform.Transform._read (/myproject/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/myproject/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
```

So, I decided to use the previous version (v4.2.2);

```
npm install --save-dev imagemin-pngquant@4.2.2
```

and then there were no problem.

Thanks.

**Comment by kevva** [comment]
Yup, haven't added support for the promised based API in `gulp-imagemin` yet. Use `4.x.x` for now.

**Comment by Takafumi-Yamashita** [comment]
Thank you for your reply.
