### ISSUE TITLE
Version 5.0.0 throws exception where 4.2.x did not

### ISSUE THREAD

**Issue by Songworks** [imagemin/imagemin-pngquant#28]
Using the package in version 5.0.0 through gulp-imagemin throws following exception:

```
/srv/projects/pnquant-test/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:740
  stream.on('end', function () {
         ^

TypeError: stream.on is not a function
    at Readable.wrap (/srv/projects/pnquant-test/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:740:10)
    at wrap (/srv/projects/pnquant-test/node_modules/stream-combiner2/index.js:67:29)
    at combine (/srv/projects/pnquant-test/node_modules/stream-combiner2/index.js:29:18)
    at Function.module.exports.obj (/srv/projects/pnquant-test/node_modules/stream-combiner2/index.js:22:10)
    at Imagemin.createStream (/srv/projects/pnquant-test/node_modules/imagemin/index.js:103:24)
    at Imagemin.run (/srv/projects/pnquant-test/node_modules/imagemin/index.js:77:20)
    at DestroyableTransform.through.obj.percent (/srv/projects/pnquant-test/node_modules/gulp-imagemin/index.js:56:12)
    at DestroyableTransform._transform (/srv/projects/pnquant-test/node_modules/through2-concurrent/through2-concurrent.js:29:15)
    at DestroyableTransform.Transform._read (/srv/projects/pnquant-test/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/srv/projects/pnquant-test/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
```

4.2.x still works though, any idea what I'm doing wrong?

Tested on node v5.11.0 with small package:

gulpfile.js
```javascript
var gulp = require('gulp');
var imagemin = require('gulp-imagemin');
var pngquant = require('imagemin-pngquant');

gulp.task('default', function ()
{
    return gulp.src('Src/**/*')
        .pipe(imagemin({
            optimizationLevel: 3,
            progressive: true,
            interlaced: true,
            use: [pngquant()]
        }))
        .pipe(gulp.dest('Build'));
});
```

package.json
```json
{
  "name": "pnquant-test",
  "version": "0.0.1",
  "description": "",
  "main": "gulpfile.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "MIT",
    "devDependencies": {
        "gulp": "^3.9",
        "gulp-imagemin": "^2.4",
        "imagemin-pngquant": "^5.0"
    }
}

```
Not counting a dummy png file.

Any further information necessary from my side?

Cheers for all the great packages!

**Comment by kevva** [comment]
https://github.com/imagemin/imagemin-pngquant/issues/26

**Comment by Songworks** [comment]
My bad. Cheers.

**Comment by kevva** [comment]
No problem. We're working on getting the newest imagemin into the gulp plugin.
