### ISSUE TITLE
Electron packed with asar throw ENOTDIR

### ISSUE THREAD

**Issue by Cherviakov** [imagemin/imagemin-pngquant#35]
Greetings. Want to report issue related to adding this packet to electron app, which then packed with asar. Asar detect executables and unpacked them in different dir, app.asar.unpacked, while pngquant still required from app.asar/node_modules resulting in that error.

Following this issue https://github.com/electron-userland/electron-builder/issues/1120 managed to fix this using this packet https://github.com/epsitec-sa/hazardous. Namely went to imagemin-pngquant directory, executed npm i hazardous, then edited index.js following way:

``` 
'use strict'
require('hazardous');
const path = require('path');
 ...
let pngquant = require('pngquant-bin');
pngquant = path.join(pngquant,'');
```

**Comment by docmars** [comment]
@Cherviakov Hmm, I tried doing this with `imagemin-pngcrush` and am getting this in my packaged app:

```
module.js:472 Uncaught Error: Cannot find module 'asar'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/andrew.merskin/Desktop/Dev Workspace/spriggan_2/build/mac/Spriggan.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/andrew.merskin/Desktop/Dev Workspace/spriggan_2/build/mac/Spriggan.app/Contents/Resources/app.asar/node_modules/hazardous/lib/index.js:5:15)
    at Object.<anonymous> (/Users/andrew.merskin/Desktop/Dev Workspace/spriggan_2/build/mac/Spriggan.app/Contents/Resources/app.asar/node_modules/hazardous/lib/index.js:98:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

- I checked `imagemin-pngcrush`'s dependencies and `node_modules` has `asar` after installing `hazardous` in the module's directory.
- I tried unpacking `imagemin` and `imagemin-pngcrush` as such:
  ```json
  "build": {
    "asarUnpack": [
      "**/node_modules/imagemin/**/*",
      "**/node_modules/imagemin-pngcrush/**/*"
    ]
  }
  ```

Did you run into this? Any ideas? Thanks! 👍

**Comment by sharifzadesina** [comment]
Same here.

**Comment by nikbabchenko** [comment]
I've forked imagemin-pngquant with @Cherviakov 's fix  https://github.com/nikbabchenko/imagemin-pngquant.

**Comment by sindresorhus** [comment]
That's a problem with Electron. Complain here: https://github.com/electron/electron/issues/9459
