### ISSUE TITLE
npm install is broken by pngquant-bin dependency

### ISSUE THREAD

**Issue by anthonyaam** [imagemin/imagemin-pngquant#46]
npm install fails with `pngquant failed to build, make sure that libpng is installed`.

[This pngquant-bin issue describes the problem in the pngquant-bin dependency](https://github.com/imagemin/pngquant-bin/issues/78).

**Comment by rogerluiz** [comment]
i have de same probleme

**Comment by tuananh** [comment]
It still fails for me with version `5.0.1`. I have to add this line to my `Dockerfile`

    apt-get install libpng-dev -y --no-install-recommends

What's the last known good version of this library?

**Comment by tyler36** [comment]
Same problem on Win10

**Comment by ArnisLielturks** [comment]
Faced the same issue.
Fixed by using older `imagemin-pngquan` library version

```npm install imagemin-pngquant@5.0.1 --save```

**Comment by coldtelling** [comment]
`npm i -D imagemin-pngquant@5.0.1`
Fixed the issue, with 4 moderate severity vulnerabilities...

**Comment by NewDiogenes** [comment]
The upgrade from 5.0.1 to 5.1.0 should not have been a major version increase, not a minor.  webpack-image-loader specifies ^5.0.0 as its dependency, meaning you need to manually edit the npm or yarn lock file to avoid this issue. A major version increment would avoid this issue.

**Comment by evinkuraga** [comment]
On a fresh laravel Install, I am getting these problems. Tried series of recommendations:

tried : 
rm -rf node_modules
rm package-lock.json yarn.lock
npm cache clear --force
npm install

tried: 
npm install cross-env

tried: 
npm install imagemin-pngquant@5.0.1 --save
npm install pngquant-bin@3.1.1 --save

tried switching 
cross-env NODE_ENV= 
to 
node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=

Nothing worked... I'm out of options. Anyone else managed to get passed this?
Again, this is a FRESH install.

**Comment by NewDiogenes** [comment]
Just realised I'm one of those terrible people who posts a problem online but never posts the solution.

I fixed this issue using yarn by adding the following to my package.json
 "resolutions": {
    "image-webpack-loader/imagemin-pngquant": "5.0.1"
  }

**Comment by evinkuraga** [comment]
@NewDiogenes  Ahh.. the smallest glimmer of hope.
Still getting this: 

`> npm run development -- --watch

npm WARN invalid config loglevel="notice"

> @ development C:\Users\sheld\Code\laravel_fresh_test
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"

module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\Users\myuser\Code\laravel_fresh_test\node_modules\laravel-mix\setup\webpack.config.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at requireConfig (C:\Users\myuser\Code\laravel_fresh_test\node_modules\webpack\bin\convert-argv.js:97:18)
    at C:\Users\myuser\Code\laravel_fresh_test\node_modules\webpack\bin\convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\myuser\Code\laravel_fresh_test\node_modules\webpack\bin\convert-argv.js:102:15)
    at yargs.parse (C:\Users\myuser\Code\laravel_fresh_test\node_modules\webpack\bin\webpack.js:171:41)
    at Object.Yargs.self.parse (C:\Users\myuser\Code\laravel_fresh_test\node_modules\yargs\yargs.js:533:18)`

Any help GREATLY appreciated!

**Comment by NewDiogenes** [comment]
Looks to me that the path to webpack.config.js is incorrect. I would recommend you not use the config file of a dependency like that, but instead copy it across into you project root. Otherwise, double check that the file actually exists at that path.

**Comment by evinkuraga** [comment]
For those like me who struggled with this even after trying all the solutions recommended, here is what I did to finally get it to work for me.

I deleted the node_modules folder (rm -rf node_modules)
I rebooted my computer
I disabled my Anti-virus
I compared my package.json to a fresh install and removed any packages that I thought might of caused issue
I ran npm install

**Then it worked.** Ultimately, I think the culprit might of been my **anti-virus (Kaspersky).** It's caused some issues before with some packages, which if really is a hassle, because when ever you run npm install / update, npm gives you an ok status even though some files might failed.

**Comment by HassanNemir** [comment]
in my case, the error happened because I was using ubuntu 18 and I was trying to run react-boilerplate, so at first the error was the image-webpack-loader, I have tried to install its dependencies and to match the versions and using older versions, but it was solved when I have installed libpng-dev on ubuntu
`sudo apt-get install libpng-dev`
 then I have tried the steps of installing boilerplate in a new repo and now it works.

**Comment by pmbuban** [comment]
> Just realised I'm one of those terrible people who posts a problem online but never posts the solution.
> 
> I fixed this issue using yarn by adding the following to my package.json
> "resolutions": {
> "image-webpack-loader/imagemin-pngquant": "5.0.1"
> }

Thanks @NewDiogenes! This is the only solution that worked for me and I've been trying to fix it for a few hours now :cry:

**Comment by adsingh14** [comment]
> Faced the same issue.
> Fixed by using older `imagemin-pngquan` and `pngquant-bin` library versions
> 
> ```
> npm install imagemin-pngquant@5.0.1 --save
> npm install pngquant-bin@3.1.1 --save```
> ```

Only the single line worked-
`npm install imagemin-pngquant@5.0.1 --save`

**Comment by Ke100n4ik** [comment]
To get this fixed I had to install libpng-dev, automake, libtool, autoconf. Then I got it compiled successfully.

It works for me, thanks!

> To get this fixed I had to install libpng-devel, automake, libtool, autoconf. Then I got it compiled successfully.

It works for me, thanks!
Little fix:
libpng-dev, not libpng-devel

**Comment by stanma** [comment]
@Ke100n4ik it is devel in Redhat/Fedora Linux. In Ubuntu/Debian it is dev.

**Comment by HassanNemir** [comment]
@bugleev what OS are you working on?

**Comment by tbruckmaier** [comment]
I just ran into the issue on npm 3.5.2, npm 6.4.1 worked fine. I could solve it for npm 3 with the fix from @adsingh14

**Comment by techouse** [comment]
Make sure you have all the prerequisites installed
`sudo apt install -y build-essential libpng-dev`

**Comment by MartinCerny-awin** [comment]
I found my solution for alpine in https://github.com/imagemin/pngquant-bin/issues/78 There are many more other solutions. Have a look there if nothing from here works for you.

**Comment by tlambrou** [comment]
On a mac simply running 
```
brew install libpng
```
worked for me.

**Comment by Aetherix** [comment]
On a mac I'm getting:

```
npm install pngquant-bin@5.0.1 --save

> pngquant-bin@5.0.1 postinstall /Users/hbrems/dev/apps/imager/node_modules/pngquant-bin
> node lib/install.js

  ⚠ Response code 503 (Backend unavailable, connection timeout)
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng is installed
    at Promise.all.then.arr (/Users/hbrems/dev/apps/imager/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

What is the backend it's trying to connect to?

**Comment by Kcharle** [comment]
raw.github.com is down right now 

https://status.github.com/messages

**Comment by miket2marcom** [comment]
@aetherix looks like this is the issue right now https://github.com/imagemin/pngquant-bin/pull/99

waiting for that fix to get merged

**Comment by Aetherix** [comment]
@Kcharle @miket2marcom Good to hear that there's a fix inbound. Thank you for the replies.

**Comment by NathanJTelford** [comment]
still getting  × Error: pngquant failed to build, make sure that libpng-dev is installed.
I'm wet behind the ears,  so I'm sure there are some things I can try to fix it. here's what I've done so far:
npm update -g gatsby-cli
npm uninstall -g gatsby-cli
npm i libpng-dev
npm i gatsby-plugin-sharp"
npm i build-essential libpng-dev

this is all on a fresh install, any suggestions?

**Comment by digidoers** [comment]
where is added make and gcc

**Comment by NguyenHiep** [comment]
I'm using ubuntu 18.04
I'm try  sudo apt-get install libpng-dev
It's work for me, thanks

**Comment by csgt** [comment]
In Centos 7,
npm install libpng-devel

worked for me

**Comment by tongjieme** [comment]
In windows 10, installation of visual studio community version helps me.

**Comment by alexerhardt** [comment]
`brew upgrade libpng`

That did it for me.

**Comment by hkniyi** [comment]
Windows Users:
1. npm install --global windows-build-tools
If the build tools installed perfectly or otherwise and npm install still fails…
2. goto C:\Users\{your PC username}\.windows-build-tools
download and extract the attached zip into  ".windows-build-tools" 
If the file already exist in the folder replace it with the extracted one.
Run the BuildTools_Full.exe with admin privilege give it time to finish the installations
3. Restart after the installation
Now everything should work fine.
Enjoy.

[BuildTools_Full.zip](https://github.com/imagemin/imagemin-pngquant/files/3439722/BuildTools_Full.zip)

**Comment by NickStees** [comment]
Windows 10 users, if you follow @hkniyi steps and still cannot install, your corporate firewall might be blocking the download. We had an https proxy firewall that was the problem.

**Comment by AshokAK12** [comment]
It works for me
"resolutions": {
"image-webpack-loader/imagemin-pngquant": "5.0.1"
}

**Comment by 16hands** [comment]
on ubuntu 18 as a normal user, this would constantly error with all the apt dependancies installed, this is for an old version of roots.io sage Wordpress starter theme which has been moved from ubuntu 16 to 18. 

Using @AshokAK12 option above in the package.json file allowed npm install to finish and we can now run yarn run build successfully, thank you

**Comment by blowsie** [comment]
@hkniyi could you breifly explain what you changed in this zip file?

**Comment by emad-sure** [comment]
@HassanNemir  thanks bro , a life saver answer

**Comment by FARCER** [comment]
$ npm install imagemin-pngquant
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ow@^0.13.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'imagemin-pngquant'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\count\AppData\Roaming\npm-cache\_logs\2019-11-03T21_25_36_299Z-debug.log

Help please

**Comment by krunal81093** [comment]
I had the same issue but it is resolved by first installing libpng-dev
using this command:
sudo apt-get install libpng-dev

**Comment by deepakkj6** [comment]
> in my case, the error happened because I was using ubuntu 18 and I was trying to run react-boilerplate, so at first the error was the image-webpack-loader, I have tried to install its dependencies and to match the versions and using older versions, but it was solved when I have installed libpng-dev on ubuntu
> `sudo apt-get install libpng-dev`
> then I have tried the steps of installing boilerplate in a new repo and now it works.

This works for Ubuntu 18. Thanks manh. You saved my day!

**Comment by alijmlzd** [comment]
I finally fixed this issue by just installing these packages:
`apt install bash gcc make libpng-dev`

**Comment by chpio** [comment]
why not use a precompiled [wasm variant](https://github.com/wapm-packages/pngquant) of pngquant?

**Comment by HydraOrc** [comment]
You can try to fix it with `apt-get install -y libpango1.0-dev` command, worked for older node v6

**Comment by benjaminpreiss** [comment]
Had the same issue. After trying all of the above answers without success I deleted node_modules folder and installed everything from the beginning:
```bash
rm -r node_modules
npm install
```

**Comment by mcljs** [comment]
Por favor alguna solución para Windows!!! Gracias! He intentado todos los metodos y nada que funciona todavia

**Comment by Qudusayo** [comment]
For Window:OS, install the **pngquant** command line tool : [Link Here](https://pngquant.org/pngquant-windows.zip), and add the path to your Enviroment Variable,  then try Install again

**Comment by SONIC3D** [comment]
For Windows OS users:

* When you install pngquant-bin through npm. (e.g: `npm install pngquant-bin@6.0.0`), The post-install step defined in package.json will try to download the pre-built binary from `https://raw.githubusercontent.com/imagemin/pngquant-bin/v6.0.0/vendor/win/pngquant.exe`. And test running it with `pngquant.exe --version` to check if the return code is zero. If it failed to get zero return, build from source would be triggered.

* For most users, using the pre-built binary is the expected way. But there are 2 common problems that would lead you into 'building from source' phase:
    1. Failed to resolve the domain name `raw.githubusercontent.com` which is commonly caused by DNS pollution.
    2. Lack of corresponding Visual C++ runtime library that `pngquant.exe` depends on. (For example, pngquant.exe@v6.0.0 relies on `VCRUNTIME140.dll`.) If you don't have the proper VC runtime library installed on your Windows OS, the post-install process would be failed in test running the downloaded binary, but it will directly catch the error and you won't see any error message box pop-up. The post-install logic then turns to build from source in the error-catch procedure.
* To solve the problems:
    1. Add the correct IP for `raw.githubusercontent.com` in the dnsmasq config file on your router or local HOST file in your Windows OS.
    2. Download and install all latest VC runtime library here: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by Pines-Cheng** [comment]
I meet this problem when I run `npm install --no-bin-links`, and `npm install` is fine, Did the result has some relation?

**Comment by the-main-thing** [comment]
On MacOS `brew install pkg-config` helps. https://stackoverflow.com/questions/62816316/gatsby-new-fails-with-pngquant-related-error

**Comment by kuleyu** [comment]
> For Windows OS users:
> 
> * When you install pngquant-bin through npm. (e.g: `npm install pngquant-bin@6.0.0`), The post-install step defined in package.json will try to download the pre-built binary from `https://raw.githubusercontent.com/imagemin/pngquant-bin/v6.0.0/vendor/win/pngquant.exe`. And test running it with `pngquant.exe --version` to check if the return code is zero. If it failed to get zero return, the 'build from source' phase would be triggered.
> * For most users, using the pre-built binary is the expected way. But there are 2 common problems that would lead you into 'building from source' phase:
>   
>   1. Failed to resolve the domain name `raw.githubusercontent.com` which is commonly caused by DNS pollution.
>   2. Lack of corresponding Visual C++ runtime library that `pngquant.exe` depends on. (For example, pngquant.exe@v6.0.0 relies on `VCRUNTIME140.dll`.) If you don't have the proper VC runtime library installed on your Windows OS, the post-install process would be failed in test running the downloaded binary, but it will directly catch the error and you won't see any error message box pop-up. The post-install logic then turns to build from source in the error-catch procedure.
> * To solve the problems:
>   
>   1. Add the correct IP for `raw.githubusercontent.com` in the dnsmasq config file on your router or local HOST file in your Windows OS.
>   2. Download and install all latest VC runtime library here: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
-----------------------------------------
"Add the correct IP for raw.githubusercontent.com in the dnsmasq config file on your router or local HOST file in your Windows OS." --- Thanks @SONIC3D , this worked for me.

#### Remarks：
> To test whether it is the first reason, we could `ping raw.githubusercontent.com` in CMD. If true, we can get the correct IP [here](https://githubusercontent.com.ipaddress.com/raw.githubusercontent.com): https://githubusercontent.com.ipaddress.com/raw.githubusercontent.com

**Comment by littlee** [comment]
I've faced the same issue for a long time. `raw.githubusercontent.com` is DNS polluted in my area.

I finally fork `imagemin-*` repos to create some mirror packages

install deps
```
npm i -D imagemin-pngquant-mirror
```

change require path
```js
const imagemin = require('imagemin');
const pngquang = require('imagemin-pngquant-mirror');
```

life gets easier from now on 👯‍♂️

**Comment by huangsiyuan2015** [comment]
> For Windows OS users:
> 
> * When you install pngquant-bin through npm. (e.g: `npm install pngquant-bin@6.0.0`), The post-install step defined in package.json will try to download the pre-built binary from `https://raw.githubusercontent.com/imagemin/pngquant-bin/v6.0.0/vendor/win/pngquant.exe`. And test running it with `pngquant.exe --version` to check if the return code is zero. If it failed to get zero return, the 'build from source' phase would be triggered.
> * For most users, using the pre-built binary is the expected way. But there are 2 common problems that would lead you into 'building from source' phase:
>   
>   1. Failed to resolve the domain name `raw.githubusercontent.com` which is commonly caused by DNS pollution.
>   2. Lack of corresponding Visual C++ runtime library that `pngquant.exe` depends on. (For example, pngquant.exe@v6.0.0 relies on `VCRUNTIME140.dll`.) If you don't have the proper VC runtime library installed on your Windows OS, the post-install process would be failed in test running the downloaded binary, but it will directly catch the error and you won't see any error message box pop-up. The post-install logic then turns to build from source in the error-catch procedure.
> * To solve the problems:
>   
>   1. Add the correct IP for `raw.githubusercontent.com` in the dnsmasq config file on your router or local HOST file in your Windows OS.
>   2. Download and install all latest VC runtime library here: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

Thanks a million! **first works for me**, I have tried many solutions, took nearly two days on this problem, but none is worked.
this answer saves me, thanks again.

**Comment by cizario** [comment]
for `Windows` users, have a look at this post for more detailed explanation : https://ryanohara.com/2020/fixing-npm-pngquant-failed-to-build-make-sure-that-libpng-dev/

**Comment by sluck430** [comment]
> For Windows OS users:
> 
> * When you install pngquant-bin through npm. (e.g: `npm install pngquant-bin@6.0.0`), The post-install step defined in package.json will try to download the pre-built binary from `https://raw.githubusercontent.com/imagemin/pngquant-bin/v6.0.0/vendor/win/pngquant.exe`. And test running it with `pngquant.exe --version` to check if the return code is zero. If it failed to get zero return, the 'build from source' phase would be triggered.
> * For most users, using the pre-built binary is the expected way. But there are 2 common problems that would lead you into 'building from source' phase:
>   
>   1. Failed to resolve the domain name `raw.githubusercontent.com` which is commonly caused by DNS pollution.
>   2. Lack of corresponding Visual C++ runtime library that `pngquant.exe` depends on. (For example, pngquant.exe@v6.0.0 relies on `VCRUNTIME140.dll`.) If you don't have the proper VC runtime library installed on your Windows OS, the post-install process would be failed in test running the downloaded binary, but it will directly catch the error and you won't see any error message box pop-up. The post-install logic then turns to build from source in the error-catch procedure.
> * To solve the problems:
>   
>   1. Add the correct IP for `raw.githubusercontent.com` in the dnsmasq config file on your router or local HOST file in your Windows OS.
>   2. Download and install all latest VC runtime library here: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

Thank you, It is useful on my win os! Just two simple steps here: 
1) Edit local dns host file and append  `raw.githubusercontent.com` ip-domain pair; 
2) download 2015-2022 vc and install it;
Then it is worked! Awesome!

**Comment by HduSy** [comment]
the bin file 'pngquant' in dependency pngquant-bin is not downloaded

**Comment by Captain890** [comment]
i solved my issue by using this command -----npm install --global windows-build-tools

**Comment by Djotchuang** [comment]
> libtool

This worked for me. Just to add that I'm using Ubuntu 20. And I had to run the installation commands with sudo.

i.e. `sudo apt-get install libpng-devel`. Do the same for the other 3 packages.

**Comment by turbodog03** [comment]
> For Windows OS users:
> 
>     * When you install pngquant-bin through npm. (e.g: `npm install pngquant-bin@6.0.0`), The post-install step defined in package.json will try to download the pre-built binary from `https://raw.githubusercontent.com/imagemin/pngquant-bin/v6.0.0/vendor/win/pngquant.exe`. And test running it with `pngquant.exe --version` to check if the return code is zero. If it failed to get zero return, the 'build from source' phase would be triggered.
> 
>     * For most users, using the pre-built binary is the expected way. But there are 2 common problems that would lead you into 'building from source' phase:
>       
>       1. Failed to resolve the domain name `raw.githubusercontent.com` which is commonly caused by DNS pollution.
>       2. Lack of corresponding Visual C++ runtime library that `pngquant.exe` depends on. (For example, pngquant.exe@v6.0.0 relies on `VCRUNTIME140.dll`.) If you don't have the proper VC runtime library installed on your Windows OS, the post-install process would be failed in test running the downloaded binary, but it will directly catch the error and you won't see any error message box pop-up. The post-install logic then turns to build from source in the error-catch procedure.
> 
>     * To solve the problems:
>       
>       1. Add the correct IP for `raw.githubusercontent.com` in the dnsmasq config file on your router or local HOST file in your Windows OS.
>       2. Download and install all latest VC runtime library here: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

Thanks a lot! I solved it by 
1. adding the correct IP for ``raw.githubusercontent.com` in the host file
2. restart the shell.  

Thank you again for the detailed answer
