### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by rehbergerp** [imagemin/imagemin-pngquant#58]
npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script 'node lib/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pngquant-bin package,
npm ERR! not with npm itself.

**Comment by dstarosta** [comment]
We are getting the same error. It looks some API call fails with a 503 status code.

```
> pngquant-bin@5.0.1 postinstall E:\Development\Git\espn-ese-adsales-customer-file\node_modules\pngquant-bin
> node lib/install.js

  ‼ Response code 503 (Backend unavailable, connection timeout)
  ‼ pngquant pre-build test failed
  i compiling from source
  × Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (E:\Development\Git\espn-ese-adsales-customer-file\node_modules\execa\index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch
```

**Comment by dstarosta** [comment]
It looks like raw.github.com is having issues. This URL throws a 503: https://raw.github.com/imagemin/pngquant-bin/v5.0.1/vendor/

**Comment by ChrissiQ** [comment]
This seems relevant:

https://github.com/imagemin/pngquant-bin/pull/99

**Comment by aarondfrancis** [comment]
https://github.com/imagemin/pngquant-bin/issues/78

**Comment by dhruvaldarji** [comment]
Same issue for my team. We require successful builds on all code changes, and this dependency of a dependency...etc. has all but brought our team to a complete halt.

**Comment by sjaurena** [comment]
Here, another one blocked by this dependency

**Comment by rehbergerp** [comment]
changed     "laravel-mix": "^1.0", to     "laravel-mix": "^2.0", and resolved my issue

**Comment by timothyis** [comment]
Looks like the solution is here: https://github.com/imagemin/pngquant-bin/pull/99

**Comment by blowsie** [comment]
I also am having issues installing on windows
```
$ npm install imagemin-pngquant

> pngquant-bin@5.0.2 postinstall C:\Projects\test\node_modules\pngquant-bin
> node lib/install.js

  ‼ unable to get local issuer certificate
  ‼ pngquant pre-build test failed
  i compiling from source
  × Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (C:\Projects\test\node_modules\execa\index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
drop-shipping-gifting@1.0.0 C:\Projects\test
+-- UNMET PEER DEPENDENCY eslint@5.16.0
`-- UNMET PEER DEPENDENCY webpack-cli@*

```

**Comment by alfa-dev** [comment]
You have to install manually.

On linux:
```bash
apt-get install libpng-dev -y --no-install-recommends
```

**Comment by HydraOrc** [comment]
On Ubuntu you can try to fix it with `apt-get install -y libpango1.0-dev` command, worked for older node v6
